# Generated by Django 4.2.5 on 2023-10-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_revision_date',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='previous_revision_date',
            field=models.DateField(default=datetime.date(2023, 10, 9)),
        ),
    ]
