# Generated by Django 4.2.5 on 2023-10-10 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='previous_revision_date',
            field=models.DateField(default=datetime.date(2023, 10, 5)),
        ),
    ]
