# Generated by Django 4.2.5 on 2023-11-03 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcard_previous_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='color',
            field=models.CharField(choices=[('red', 'Color 1'), ('blue', 'Color 2'), ('green', 'Color 3'), ('yellow', 'Color 4'), ('pink', 'Color 5')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_revision_date',
            field=models.DateField(default=datetime.date(2023, 11, 3)),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='previous_revision_date',
            field=models.DateField(default=datetime.date(2023, 10, 29)),
        ),
    ]
