# Generated by Django 4.2.5 on 2023-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_chapter_color_alter_flashcard_next_revision_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='color',
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('red', 'Color 1'), ('blue', 'Color 2'), ('green', 'Color 3'), ('yellow', 'Color 4'), ('pink', 'Color 5')], default='red', max_length=10),
        ),
    ]
